load("//build/kernel/kleaf:kernel.bzl", "kernel_module")
load("//kernel6.1:unisoc_bazels/unisoc_constants.bzl", "UNISOC_SOC")

kernel_module(
    name = "sprdbt_tty",
    srcs =["//unisoc_modules/kernel6.1/wcn/include:unisoc-wcn-include"] +
	glob([
        "**/*.c",
        "**/*.h",
        "**/Kbuild",
        "**/Makefile",
    ]),
    outs = ["sprdbt_tty.ko"],

    kernel_build = "//kernel6.1:{soc}".format(soc=UNISOC_SOC),
    visibility = ["//visibility:public"],
    deps = [
        "//unisoc_modules/kernel6.1/wcn/bsp/unisoc_wcn_bsp:unisoc_wcn_bsp",
    ],
)
