#
# sprd_fm.ko
#
# Kbuild: for kernel building external module
#
# Note:
# - Please refer to modules/sample/Kbuild to find out what should be
#   done is this Kbuild file
#

ifeq ($(strip $(BSP_BOARD_UNISOC_WCN_SOCKET)),sipc2)
    FM_DEVICE := fm_515
else ifeq ($(strip $(BSP_BOARD_UNISOC_WCN_SOCKET)),sdio)
    FM_DEVICE := fm_515
else ifeq ($(strip $(BSP_BOARD_UNISOC_WCN_SOCKET)),sipc)
    FM_DEVICE := fm_$(strip $(BSP_BOARD_UNISOC_WCN_SOCKET))
else ifeq ($(strip $(BSP_BOARD_UNISOC_WCN_SOCKET)),pcie)
    FM_DEVICE := fm_$(strip $(BSP_BOARD_UNISOC_WCN_SOCKET))
else
    $(error no BSP_BOARD_UNISOC_WCN_SOCKET, pls fix it !!!)
endif


#
# Source List
#
KO_MODULE_NAME := sprd_fm
KO_MODULE_PATH := $(src)/$(FM_DEVICE)
KO_MODULE_SRC  :=

KO_MODULE_SRC += \
	$(wildcard $(KO_MODULE_PATH)/*.c)

#
# Build Options
#
ccflags-y += -DDEBUG

#
# Final Objects
#
obj-m := $(KO_MODULE_NAME).o
# Comment it if the only object file has the same name with module
$(KO_MODULE_NAME)-y := $(patsubst $(src)/%.c,%.o,$(KO_MODULE_SRC))
