#
# sprd_wlan_combo.ko
#
# Kbuild: for kernel building external module
#
# Note:
# - Please refer to modules/sample/Kbuild to find out what should be
#   done is this Kbuild file
#

ifeq ($(TARGET_BUILD_VARIANT),userdebug)
ccflags-y += -DCONFIG_SPRD_WLAN_DEBUG
endif

ccflags-y += -DCONFIG_SPRD_WLAN_VENDOR_SPECIFIC
# ccflags-y += -DCONFIG_SC2355_WLAN_NAN
# ccflags-y += -DCONFIG_SC2355_WLAN_RTT

KO_MODULE_NAME := sprd_wlan_combo
KO_MODULE_PATH := $(src)

ccflags-y += -I$(KO_MODULE_PATH)
ccflags-y += -I$(KO_MODULE_PATH)/common
ccflags-y += -I$(KO_MODULE_PATH)/sc2332
ccflags-y += -I$(KO_MODULE_PATH)/sc2355

#
# Final Objects
#
obj-m := $(KO_MODULE_NAME).o

SPRD_WLAN_COMMON := \
		common/sprd_wlan.o \
		common/cfg80211.o \
		common/debug.o \
		common/delay_work.o \
		common/iface.o \
		common/msg.o \
		common/npi.o \
		common/report.o \
		common/tdls.o

SC2332_WLAN := \
		sc2332/acs.o \
		sc2332/init.o \
		sc2332/cmdevt.o \
		sc2332/qos.o \
		sc2332/scan.o \
		sc2332/tcp_ack.o \
		sc2332/txrx.o \
		sc2332/fcc.o \
		sc2332/vendor.o \
		sc2332/wapi.o

SC2332_SIPC_WLAN := sc2332/sipc.o

SC2332_SDIO_WLAN := sc2332/sdio.o

SC2355_WLAN := \
		sc2355/acs.o \
		sc2355/api_version.o \
		sc2355/cmdevt.o \
		sc2355/defrag.o \
		sc2355/hw_param.o \
		sc2355/init.o \
		sc2355/mm.o \
		sc2355/qos.o \
		sc2355/reorder.o \
		sc2355/rx.o \
		sc2355/scan.o \
		sc2355/tcp_ack.o \
		sc2355/tx.o \
		sc2355/fcc.o \
		sc2355/vendor.o \
		sc2355/nan.o \
		sc2355/rtt.o

SC2355_SDIO_WLAN := sc2355/sdio.o

SC2355_PCIE_WLAN := \
		sc2355/pcie.o \
		sc2355/pcie_buf.o

$(KO_MODULE_NAME)-y += \
		$(SPRD_WLAN_COMMON) \
		$(SC2332_WLAN) \
		$(SC2332_SIPC_WLAN) \
		$(SC2355_WLAN) \
		$(SC2355_SDIO_WLAN)
